version: '3.8'

services:
  local-agent:
    build: 
      context: .
      ssh: 
        - default
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
    environment:
      - MIX_ENV=dev
      - PHOENIX_LIVE_RELOAD=true
    env_file:
      - .env
    command: bash -c "mix do deps.get, deps.compile && mix phx.server"
    # Enable inotify events
    privileged: true

volumes:
  deps:
  build: 